# -*- coding: utf-8 -*-
# Generated by Django 1.10b1 on 2016-07-12 10:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StockDb',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currentDate', models.DateField()),
                ('open_st', models.FloatField()),
                ('high', models.FloatField()),
                ('low', models.FloatField()),
                ('close', models.FloatField()),
                ('volume', models.FloatField()),
                ('adjClose', models.FloatField()),
                ('stock', models.IntegerField()),
            ],
            options={
                'db_table': 'stockdatabase',
            },
        ),
    ]
