# -*- coding: utf-8 -*-
# Generated by Django 1.10b1 on 2016-07-12 11:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stockdatabase', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockdb',
            name='volume',
            field=models.IntegerField(),
        ),
    ]
